//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quiz_Master
{
    public partial class Reports
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label emp_name;
        protected global::System.Web.UI.WebControls.Label emp_id;
        protected global::System.Web.UI.WebControls.Repeater  Repeater_1;
        protected global::System.Web.UI.WebControls.Repeater Repeater_2;

    }
}

